language: python

python:
  - "3.6"

dist: xenial

before_script:
  - pip install -r requirements.txt

script:
    - python check_env.py
    - python 1/1.py

sudo: required

after_success:
    - echo Success